spring:
  application:
    name: transaction-ingestion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_risk_engine
    username: transaction_risk_user
    password: transaction_risk_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 5

    consumer:
      group-id: transaction-ingestion-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


transaction-risk-engine:
  kafka:
    topics:
      transaction-created: transaction.created.v1
