import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import { Badge } from "../../../components/ui/Badge";
import { Card } from "../../../components/ui/Card";
import { getRiskDecisions } from "../api/riskDecisionApi";
import type { RiskDecision } from "../types";

function riskVariant(level: RiskDecision["riskLevel"]) {
  if (level === "CRITICAL") return "danger";
  if (level === "HIGH") return "warning";
  if (level === "MEDIUM") return "neutral";
  return "success";
}

export function RiskDecisionsPage() {
  const { data, isLoading, isError } = useQuery({
    queryKey: ["risk-decisions"],
    queryFn: getRiskDecisions,
    refetchInterval: 5000,
  });

  if (isLoading) return <p>Loading risk decisions...</p>;
  if (isError) return <p>Failed to load risk decisions.</p>;

  return (
    <div>
      <h2>Risk Decisions</h2>
      <p className="page-description">
        Risk decisions generated by the risk-engine-service.
      </p>

      <Card>
        <table className="data-table">
          <thead>
            <tr>
              <th>Transaction</th>
              <th>Score</th>
              <th>Risk Level</th>
              <th>Status</th>
              <th>Reason</th>
              <th>Evaluated</th>
            </tr>
          </thead>
          <tbody>
            {data?.map((decision) => (
              <tr key={decision.transactionId}>
                <td>
                  <Link to={`/risk-decisions/${decision.transactionId}`}>
                    {decision.transactionReference}
                  </Link>
                </td>
                <td>{decision.riskScore}</td>
                <td>
                  <Badge variant={riskVariant(decision.riskLevel)}>
                    {decision.riskLevel}
                  </Badge>
                </td>
                <td>{decision.decisionStatus}</td>
                <td>{decision.decisionReason}</td>
                <td>{new Date(decision.evaluatedAt).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </Card>
    </div>
  );
}